### ISSUE TITLE
Create a GET handler for /componenttype/<ct_name>

### ISSUE THREAD

**Issue by Spredzy** [redhat-cip/dci-control-server#1]
Currently we can only retrieve component type by ids when querying the API.
Since name must be unique (enforced by a PK at the db level), an endpoing /componenttype/<ct_name> should be provided in order to retrieve componenttype information by its name.

**Comment by ylamgarchal** [comment]
componenttype resource is not available anymore.

This is replaced by a field 'type' in component.
