### ISSUE TITLE
the remoteCIs are not scoped to teams

### ISSUE THREAD

**Issue by IxDay** [redhat-cip/dci-control-server#11]
I do not know if it is a normal behaviour but when connecting with a user we get all the remoteCIS even those which don't belong to the user team

**Comment by ylamgarchal** [comment]
Could you put the query and the result here

**Comment by IxDay** [comment]
It is already fixed need review here: http://softwarefactory-project.io/r/#/c/2304/

**Comment by IxDay** [comment]
closed by https://github.com/redhat-cip/dci-control-server/commit/6a53c81fa85b2433e21a0271c751096bf1409a8f
