### ISSUE TITLE
the jobs should be sort according to the last update

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-control-server#16]
I created a large list of empty jobs some days ago. Now the interface is a bit confusing because it list all these jobs as if they were old. Actually, some of them have just been proceed today and I cannot find them easily in the list.

**Comment by IxDay** [comment]
already closed by: https://github.com/redhat-cip/dci-control-server/commit/3555bd92e66e0fdf865bccd71b458c2758952ee6
