### ISSUE TITLE
Raise a 409 Conflict or 422 Entity Already exist where appropriate

### ISSUE THREAD

**Issue by Spredzy** [redhat-cip/dci-control-server#2]
Currently if we try to add a new componenttype that already exists in the db we end up with a 400 and the psycopg2 issue.

This should be abstracted and a proper 409/422 http error should be returned

**Comment by IxDay** [comment]
Those commits fix this issue:
- https://github.com/redhat-cip/dci-control-server/commit/79a8478792f24f8b0422c6a60331b72e0ff79513
- https://github.com/redhat-cip/dci-control-server/commit/90be04bbe40fcb29677da07a128ff92da4a829cd
- https://github.com/redhat-cip/dci-control-server/commit/167ea3a766b28823b97cece5b80e33ff1c65e118
