### ISSUE TITLE
Logs order.

### ISSUE THREAD

**Issue by gaelrehault** [redhat-cip/dci-control-server#28]
web UI - looking at the job output , the order of the logs would make more sense reversed 
Current : most recent to eldest
Would make more sense : eldest to most recent

**Comment by goneri** [comment]
I agree with @gaelrehault, the jobstatus should be ordered in chronological order. It's really confusing to have to scowl all the time to find the beginning of a section.

**Comment by Spredzy** [comment]
I kinda disagree here. When I run a job and it fails, I am more interested in the error (ie. the latest jobstates and its log) rather than having to scroll down to look the root cause it failed. My 2cts.

**Comment by goneri** [comment]
@Spredzy, each sections of the logs have to be read from the top to the bottom but we have to jump from the bottom to the top in the list of jobstatus.
We already fold the logs to simplify the scrolling.

**Comment by Spredzy** [comment]
@goneri to me - and indeed it is a personal opinion - it is better that way. Have the latest update on the top. Yet different users might have different preferences. We could have it sorted chronologically (by default) - as requested by @gaelrehault - and have a button to have it ordered un-chornologically.

@MaxV: What do you think ?
