### ISSUE TITLE
Add issues in job embed

### ISSUE THREAD

**Issue by guillaumevincent** [redhat-cip/dci-control-server#45]
To simplify the user interface it will be interesting to allow `issues` embed for job

**Comment by goneri** [comment]
This one is not trivial because the issues are not just a SQL table. An extra processing is done with Python. We can still skip this second part and just get the raw bug URL.

**Comment by guillaumevincent** [comment]
I understand but @goneri maybe in job.issues we can only get the urls 

    ['url1', 'url2']

**Comment by goneri** [comment]
This is what I was proposing :-)

**Comment by guillaumevincent** [comment]
yes sorry, didn't read the entire comment
