### ISSUE TITLE
Avoid double GET on '/jobs/<uuid:job_id>'

### ISSUE THREAD

**Issue by guillaumevincent** [redhat-cip/dci-control-server#46]
GET on `/jobs/<uuid:job_id>` is slow, really slow.
It can take up to 8sec.

One reason is that we get job in db twice see https://github.com/redhat-cip/dci-control-server/blob/master/dci/api/v1/jobs.py#L499-L507

**Comment by Spredzy** [comment]
@guillaumevincent Is is still an issue ?
