### ISSUE TITLE
scheduler should ignore components with no file

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-control-server#55]
We had a case today where the scheduler job with a component that was empty. There were no component_file associated.

The scheduler should skip this kind of component.

**Comment by goneri** [comment]
Actually, this is a bug with the feeder. The component should not be created with statue=active.

**Comment by Spredzy** [comment]
@Goneri this has been fixed in dci-feeder-api. Process is create a new component in inactive, upload component, if all went fine move status to active. Feel free to re-open if you think it hasn't been fully adressed.
