### ISSUE TITLE
As a PO I cannot subscribe to remoteci from the sub-team

### ISSUE THREAD

**Issue by goneri** [redhat-cip/dci-control-server#60]
I've the visibility to several teams. When I try to subscribe to a remoteci from one of then, I get the following error:

POST on: https://api.distributed-ci.io/api/v1/remotecis/dcdef03c-7938-4536-a6b9-e96a9d879af2/users

Req:
```json
{
"user_id": "51bd34bf-5767-48c2-aeae-b49212480533"
}
```

Response:
```json
{
  "message": "Operation not authorized.",
  "payload": {},
  "status_code": 401
}
```

**Comment by cedlecomte** [comment]
It's fixed since 8adc706e0c864ed50af937ccf6844556a4556338
