### ISSUE TITLE
Can't re-create a component if it has been deleted previously.

### ISSUE THREAD

**Issue by fcharlier** [redhat-cip/dci-control-server#64]
How to reproduce:

1. Create a component named 'A'
2. Delete the component
3. Create a component named 'A' again.

What happens:

the API answers with:
```{
    "status_code": 409, 
    "message": "conflict on components", 
    "payload": {
        "error": {
            "name": "already_exists"
        }
    }
}
```

What should happen:

Once a component has been deleted, we should be able to create a  new one with the same name.

**Comment by dsavineau** [comment]
That's the expected workflow because we're using soft-delete. If you want to reuse the same name, then you need to purge the corresponding resource first.

**Comment by fcharlier** [comment]
I proposed a patchset to allow having for a given name:
- [0-1] component in active state
- [0-n] component(s) in other states.

https://softwarefactory-project.io/r/12197
