### ISSUE TITLE
Create a team is not working as expected : "parent_id not a valid team id"

### ISSUE THREAD

**Issue by guillaumevincent** [redhat-cip/dci-control-server#66]
control server try to get parent team if parent_id is null.
We cannot create a root team (without a parent_id)

```
POST /teams

{
  name: 'root team',
  external: true,
  parent_id:null
}
```

raise a 400 `parent_id not a valid team id`

**Comment by fcharlier** [comment]
The current behaviour when `parent_id` is null is to create a team which is a children of the current user's team.

There can be only one root team, the 'admin' team, which is created during server bootstrap, other teams are, at best, children of the admin team.

**Comment by fcharlier** [comment]
So I'm tempted to close this as not a bug.

**Comment by guillaumevincent** [comment]
Yes I will update the frontend. Thanks
