### ISSUE TITLE
softwarefactory-project.io/r/dci-control-server 404

### ISSUE THREAD

**Issue by wking** [redhat-cip/dci-control-server#84]
```console
$ git clone --depth 1 https://github.com/redhat-cip/dci-control-server
$ cd dci-control-server
$ git --no-pager grep softwarefactory-project.io
.gitreview:host=softwarefactory-project.io
README.md:1.  clone the repository: <http://softwarefactory-project.io/r/dci-control-server>
$ curl -iLs http://softwarefactory-project.io/r/dci-control-server | grep -i '^HTTP\|^Location'
HTTP/1.1 301 Moved Permanently
Location: https://softwarefactory-project.io/r/dci-control-server
HTTP/1.1 404 Not Found
```

The location is also listed on https://softwarefactory-project.io/project/Distributed-CI .  I'm not familiar with software-factory, but it seems like something needs to be updated.

**Comment by fcharlier** [comment]
Hi @wking 

The github repositories for DCI are mirrors of the ones on SoftwareFactory where we do our reviews, CI, etc. …

If you only need the software, don't worry about the SoftwareFactory repositories.

If you want to contribute patches, then it's best to clone directly from the SoftwareFactory repository.
As the README.md states, you can simply clone the repository from the URL mentionned:
```
❯ git clone 'https://softwarefactory-project.io/r/dci-control-server'
Cloning into 'dci-control-server'...
remote: Counting objects: 15341, done
remote: Finding sources: 100% (15341/15341)
remote: Total 15341 (delta 9712), reused 13875 (delta 9712)
Receiving objects: 100% (15341/15341), 4.83 MiB | 6.83 MiB/s, done.
Resolving deltas: 100% (9712/9712), done.
```

You'll then have to setup git-review (`git review -s`) to setup the gerrit remotes.
There's a comprehensive documentation on how gerrit works hosted on SoftwareFactory: https://softwarefactory-project.io/r/Documentation/index.html
